format_version = 2

[apps.GLFWMetalApp]
identifier = 'foundation.wabi.GLFWMetalApp'
product = 'GLFWMetalApp'
version = '1.0.0'
category = 'public.app-category.graphics-design'

[apps.GLFWMetalApp.plist]
commit = '$(COMMIT_HASH)'
